import { getDb } from "@/lib/db";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/Navbar"
import "./globals.css";
import { PlaybackBar } from "./components/PlaybackBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const db = getDb();

  const initialSongs = await db
    .selectFrom("songs")
    .innerJoin("albums", "songs.album_id", "albums.id")
    .innerJoin("authors", "albums.author_id", "authors.id")
    .select([
      "songs.id",
      "songs.name",
      "authors.name as author",
      "songs.duration",
    ])
    .limit(5)
    .execute();

  const playlists = await db.selectFrom('playlists').where('user_id', '=', 1).selectAll().execute();

  console.log(initialSongs);


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="pb-4">{children}</div>

        <div className="fixed top-0 left-0 right-0">
          <Navbar />
        </div>
        <div className="fixed h-24 bg-base-100 bottom-0 left-0 right-0 inset-shadow-sm">
          <PlaybackBar initialSongs={initialSongs} playlists={playlists} />
        </div>

      </body>
    </html>
  );
}
